// <auto-generated />
namespace JassServerModel2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class removeactivitylog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeactivitylog));
        
        string IMigrationMetadata.Id
        {
            get { return "201312020128436_remove-activity-log"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
