// <auto-generated />
namespace JassServerModel2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class estimatedStartHour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(estimatedStartHour));
        
        string IMigrationMetadata.Id
        {
            get { return "201409062139187_estimatedStartHour"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
